name: Test

on: [push, pull_request]

jobs:
  ruby:
    strategy:
      fail-fast: false
      matrix:
        ruby_version: ["2.7", "head"]
        rails_version: ["main", "6-0-stable", "6-1-stable"]
    runs-on: ubuntu-latest
    name: Test on ${{ matrix.ruby_version }} with Rails ${{ matrix.rails_version }}
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby_version }}
    - name: Install dependencies
      run: |
        gem update --system
        gem i bundler
        bundle install --jobs 4 --retry 3
      env:
        RAILS_VERSION: ${{ matrix.rails_version }}
    - name: Run tests
      run: |
        bundle exec rake
      env:
        RAILS_VERSION: ${{ matrix.rails_version }}
  jruby:
    strategy:
      fail-fast: false
      matrix:
        ruby_version: ["jruby"]
        rails_version: ["6-0-stable", "6-1-stable"]
    runs-on: ubuntu-latest
    name: Test on ${{ matrix.ruby_version }} with Rails ${{ matrix.rails_version }}
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby_version }}
    - name: Install dependencies
      run: |
        gem update --system
        gem i bundler
        bundle install --jobs 4 --retry 3
      env:
        RAILS_VERSION: ${{ matrix.rails_version }}
    - name: Run tests
      run: |
        bundle exec rake
      env:
        RAILS_VERSION: ${{ matrix.rails_version }}
